name: tidb-ai

services:
  backend:
    image: tidb.ai/backend:local
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:80"
    env_file:
      - ./backend/.env
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  frontend:
    image: tidb.ai/frontend:local
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      BASE_URL: http://backend
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  redis:
    image: redis:6.0.16
    restart: always
    volumes:
      - ./redis-data:/data

  background:
    image: tidb.ai/backend:local
    build:
      context: ./backend
    restart: always
    depends_on:
      - redis
    ports:
      - "5555:5555"
    env_file:
      - ./backend/.env
    command: /usr/bin/supervisord
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"
