name: Publish Docker Images For Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to build the image with"
        required: true

jobs:
    build-backend:
      name: Build and Push Backend Image
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write
      steps:
        -
          name: Checkout
          uses: actions/checkout@v4
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.RELEASE_DOCKERHUB_USERNAME }}
            password: ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Build and push backend
          uses: docker/build-push-action@v6
          with:
            context: backend
            platform: linux/amd64,linux/arm64
            push: true
            tags: |
                ${{ secrets.RELEASE_DOCKERHUB_USERNAME }}/backend:${{ inputs.tag || github.ref_name }}

    build-frontend:
      name: Build and Push Frontend Image
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write
      steps:
        -
          name: Checkout
          uses: actions/checkout@v4
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.RELEASE_DOCKERHUB_USERNAME }}
            password: ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Build and push frontend
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./frontend/Dockerfile
            platform: linux/amd64,linux/arm64
            push: true
            tags: |
                ${{ secrets.RELEASE_DOCKERHUB_USERNAME }}/frontend:${{ inputs.tag || github.ref_name }}