name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-frontend:
    name: Verify frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
          package_json_file: ./frontend/package.json
      - run: pnpm run verify
